---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart random-ping
  systemd:
    name: random-ping-targets
    state: restarted

- name: restart blackbox
  community.docker.docker_compose_v2:
    project_src: /opt/monitoring/random-ping
    state: present
    recreate: always
