---
# roles/random_ping/handlers/main.yml
- name: restart blackbox-random-ping
  community.docker.docker_compose_v2:
    project_src: "{{ random_ping_dir | default('/opt/monitoring/blackbox-random-ping') }}"
    state: present
    recreate: always
  become: true
