---
- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
  become: true

- name: Reload keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: reloaded
  become: true
