---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true

- name: Restart chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted
  become: true

- name: Save iptables rules
  ansible.builtin.shell:
    cmd: netfilter-persistent save
  become: true
