---
# playbooks/03-keepalived.yml
- name: "🔁 [03/12] Cài đặt Keepalived (VIP Failover)"
  hosts: monitoring_lb
  become: true
  gather_facts: false
  tags: [keepalived, ha, network]
  roles:
    - role: keepalived
      tags: keepalived
