---
# inventory/group_vars/monitoring_alertmanager.yml
# Biến riêng cho alertmanager nodes

# Cluster peers tự tính từ group
alertmanager_peers: >-
  {{ groups['monitoring_alertmanager']
     | map('extract', hostvars, 'ansible_host')
     | map('regex_replace', '$', ':' + alertmanager_cluster_port | string)
     | list }}
